name: shell-ci

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

permissions:
  contents: read

jobs:
  tests:
    name: Run shunit2 tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run shunit2 tests
        uses: sudo-bot/action-shunit2@latest
        with:
          cli: "./tests/bash-map.test.sh"

  shellcheck:
    name: Run ShellCheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@master
        with:
          check_together: "yes"
